spring:
  #swagger2 Config
  #springboot version >= 2.6
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #指定选择的运行环境
#  profiles:
#    active: dev
  application:
    name: partner-matching
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/partner-matching
    username: root
    password: 1234
  #session timeout session超时
  session:
    timeout: 86400
    store-type: redis
  #redis 配置
  redis:
    port: 6379 #端口
    host: localhost #地址 这里用本地
    database: 0 #用哪一个db库

server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie: #规定可以携带cookie的域名
        domain: localhost
        same-site: lax
        secure: false # http协议

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # logic deleted entity names 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # Logic deleted (default 1)逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # Logic not deleted (default 0) 逻辑未删除值(默认为 0)
